<a href="https://colab.research.google.com/github/CosmoStat/Tutorials/blob/tensorflow-tutorial/TensorFlowFirstSteps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Copyright 2020 Francois Lanusse, Zaccharie Ramzi

Licensed under the Apache License, Version 2.0 (the "License");


# First steps with TensorFlow

Authors: [@EiffL](https://github.com/EiffL) (Francois Lanusse), [@zaccharieramzi](https://github.com/zaccharieramzi) (Zaccharie Ramzi)

## Overview

In this short notebook, we will review the basics of TensorFlow, how to write a computational graph, compute gradients by automatic differentiation, and perform optimization. This introduction is intended for first time TensorFlow users, and can be safely disregarded by experienced users.  
**Note**: we only consider TensorFlow 2.x here.

### Learning goals

In this notebook, we will learn:
  - Core principles of TensorFlow
  - How to write a computational graph
  - How to compute gradients
  - How to perform optimization

## What is a Tensor?

Let us get started with a minimal example:

In [0]:
import numpy as np
import tensorflow as tf

x = tf.zeros(shape=[8])

This code is pretty much self explanatory, we have defined an object x to be an "array" of zeros of size 16. Let's take a closer look at this object:

In [8]:
x

<tf.Tensor: shape=(8,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

We see that this object is in fact a TensorFlow Tensor, characterized by:
  - A shape, e.g. (8,)
  - A type: noted as `dtype`, here by default a single precision float i.e. `float32`, but types include `int32`, `float64`, `complex64`, etc.

**TODO**: explain that tensors are abstract objects, not values

**TODO**: explain why float32 is default

In addition, we see that this tensor has an assigned value, denoted by a numpy array, filled with zeros in this instance. 

**TODO**: explain that if we see a value it's because of eager execution


A numpy array can be converted into a TensorFlow tensor and vice-versa easily using the `tf.convert_to_tensor` function and `.numpy()` member of Tensor objects:

In [9]:
# Define a numpy array:
x = np.array( [1., 2., 3., 4.])

# Convert it into a tensor:
a = tf.convert_to_tensor( x )

# Inspect Tensor a:
a

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>

In [10]:
# Convert back this tensor into a numpy array
y = a.numpy()

# Inspect array y:
y

array([1., 2., 3., 4.])

## Defining computational graphs

Now that we have introduced the notion of Tensors, let's learn about the Flow part :-) 

TensorFlow defines computations in terms of simple **operations** (`ops` for short) which can manipulate, create, or destroy tensors. These `ops`can be stringed together into a computational graph in order to perform complex operations.

Let us consider a very simple computation: $y = a * x + b$  
In the general case `y`, `a`, `y`, and `b` are all tensors, and the fundamental `ops` needed here are `add` and `multiply`. Here is how the computational graph would look like:
```
                              a        x
                              \        /
                                mutliply
                                  |    b         
                                  \   /
                                    add
                                    |
                                    y
```
writing this computation in tensorflow is extremely simple:

In [0]:
# Let's introduce the input tensors
a = tf.ones(shape=(4,))
b = tf.zeros(shape=(4,))
x = tf.convert_to_tensor(np.array([1., 2., 3., 4.]), dtype=tf.float32)

# And here we define the computation
y = a * x + b

In [16]:
y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

Feel free to experiment with the code above, in particular, try changing the shape or dtypes of the input tensors, what happens?

Because TF 2 uses eager execution, everything seems to happen at once, and it is not clear when the graph is created and executed. 

It is possible to define explicitly a graph that will be executed in one piece, i.e. without costly back and forth between python and GPU code using the `tf.function` decorator. Consider this example:

In [0]:
def affine_transform(x, a, b):
  return a * x + b

In [20]:
affine_transform(1 , 2 , 3)

5

This is pure Python code, and return a Python integer. No TensorFlow is involved here at all.

Now let's add the `@tf.function` decorator and see what happens:

In [0]:
@tf.function
def affine_transform(x, a, b):
  return a * x + b

In [22]:
affine_transform(1 , 2 , 3)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

We see that this function now returns a tensor, despite being provided pure Python integer.

**TODO**: the magic of autograph

## Computing gradients

The most important part of TensorFlow is automatic differentation. 

## Optimization